project:
  type: website

website:
  title: "Looking for a thousand buddhas"
  sidebar:
    logo: /images/green-buddhist-bodhi-leaf-removebg-preview.png
    style: docked  
    collapse-level: 1
    background: light
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd
format:
  html:
    toc: true
    toc-location: left
    grid:
      margin-width: 350px
    theme:
      - sandstone
      - gampopa.scss
    css: styles.css
reference-location: margin
citation-location: margin




